export const metadata = {
    title: 'Users',
    description: 'Generated by Next.js',
}

export default function UserLayout({ children }) {
    return (
        <div className="userLayout">
            {children}
        </div>
    )
}
  